server:
  port: 80
  servlet:
    context-path: /test123

country: china

user1:
  name: zhangsan

likes:
  - game
  - sese
  - sleep

baseDir: c:\windows10

#使用${}引用数据
#使用""包裹的字符串，转义字符可以生效 制表符之类的也可以
tempDir: "${baseDir}\temp"

#创建类，用于封装下面的数据
#有spring帮我们去加载数据到对象中，一定要告诉spring加载这组信息
#使用的时候从spring中直接获取信息使用
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: ytyt420ztzt

